#!/usr/bin/env bash
# Demo the local CDP Stripe Elements PCI iframe technique
# Run on birchcoffee.com checkout page (or any Shopify checkout)
# This script documents the correct sequence — it's a reference, not directly executable.
echo "== Stripe Elements PCI Iframe Technique (Local CDP) =="
echo ""
echo "Target checkout: https://www.birchcoffee.com/checkouts/cn/TOKEN/en-us"
echo ""
echo "1. Navigate to checkout page (use browser_navigate)"
echo "2. Fill address/shipping fields (use browser_click + browser_type)"
echo "3. Get targets via CDP:"
echo "   browser_cdp method=Target.getTargets"
echo ""
echo "4. Find Stripe Elements iframe targets (number-ltr, expiry-ltr, verification_value-ltr)"
echo "   These appear as type='iframe' targets in Target.getTargets"
echo ""
echo "5. Focus the card number iframe input:"
echo "   browser_cdp method=Runtime.evaluate params={\"expression\":\"...\",\"target_id\":\"...\"}"
echo ""
echo "6. Type card number via insertText:"
echo "   browser_cdp method=Input.insertText params={\"text\":\"4866560003147814\"}"
echo ""
echo "7. Repeat for expiry (0129) and CVC (653)"
echo ""
echo "8. Click Pay/Place Order button"
echo ""
echo "IMPORTANT:"
echo "- NEVER use .value = or dispatchEvent — Stripe ignores them"
echo "- ALWAYS use Input.insertText (real keystroke simulation)"
echo "- Local Chrome runs on --remote-debugging-port=9222"
echo "- Browserbase only needed for Steam/PayPal/Amazon/Apple"
